#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PRESERVE_KUSONIME_ENRICH_LIMIT="${KUSONIME_ENRICH_LIMIT-}"
PRESERVE_KUSONIME_ENRICH_SKIP_EXISTING="${KUSONIME_ENRICH_SKIP_EXISTING-}"
PRESERVE_KUSONIME_ENRICH_MIN_MATCH_SCORE="${KUSONIME_ENRICH_MIN_MATCH_SCORE-}"
PRESERVE_KUSONIME_ENRICH_SLUGS="${KUSONIME_ENRICH_SLUGS-}"
PRESERVE_KUSONIME_BASE_URL="${KUSONIME_BASE_URL-}"
PRESERVE_KUSONIME_USER_AGENT="${KUSONIME_USER_AGENT-}"
PRESERVE_KUSONIME_HTTP_TIMEOUT="${KUSONIME_HTTP_TIMEOUT-}"

if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi

[[ -n "${PRESERVE_KUSONIME_ENRICH_LIMIT}" ]] && export KUSONIME_ENRICH_LIMIT="${PRESERVE_KUSONIME_ENRICH_LIMIT}"
[[ -n "${PRESERVE_KUSONIME_ENRICH_SKIP_EXISTING}" ]] && export KUSONIME_ENRICH_SKIP_EXISTING="${PRESERVE_KUSONIME_ENRICH_SKIP_EXISTING}"
[[ -n "${PRESERVE_KUSONIME_ENRICH_MIN_MATCH_SCORE}" ]] && export KUSONIME_ENRICH_MIN_MATCH_SCORE="${PRESERVE_KUSONIME_ENRICH_MIN_MATCH_SCORE}"
[[ -n "${PRESERVE_KUSONIME_ENRICH_SLUGS}" ]] && export KUSONIME_ENRICH_SLUGS="${PRESERVE_KUSONIME_ENRICH_SLUGS}"
[[ -n "${PRESERVE_KUSONIME_BASE_URL}" ]] && export KUSONIME_BASE_URL="${PRESERVE_KUSONIME_BASE_URL}"
[[ -n "${PRESERVE_KUSONIME_USER_AGENT}" ]] && export KUSONIME_USER_AGENT="${PRESERVE_KUSONIME_USER_AGENT}"
[[ -n "${PRESERVE_KUSONIME_HTTP_TIMEOUT}" ]] && export KUSONIME_HTTP_TIMEOUT="${PRESERVE_KUSONIME_HTTP_TIMEOUT}"

exec go run ./cmd/kusonime-enrich
